/**
 * Firebase initialization for Pakalorie FYP.
 *
 * @react-native-firebase auto-initializes from the native config files
 * (google-services.json on Android, GoogleService-Info.plist on iOS) — there's
 * no explicit `initializeApp` call here. This module re-exports the auth and
 * firestore singletons so consumers don't import RNFirebase modules directly.
 *
 * If you ever need to verify init succeeded:
 *   import { getApp } from '@react-native-firebase/app';
 *   console.log(getApp().options.projectId);
 */

import auth, { type FirebaseAuthTypes } from '@react-native-firebase/auth';
import firestore, { type FirebaseFirestoreTypes } from '@react-native-firebase/firestore';
import {
  GoogleSignin,
  statusCodes as googleSigninStatusCodes,
} from '@react-native-google-signin/google-signin';

/**
 * Configure Google Sign-In once per app start. Call this from the root layout
 * (app/_layout.tsx) before rendering AuthProvider.
 *
 * `webClientId` is the OAuth 2.0 Web client ID generated by Firebase when you
 * enable Google as a sign-in provider — find it under Firebase Console →
 * Authentication → Sign-in method → Google → Web SDK configuration.
 */
export function configureGoogleSignIn(webClientId: string): void {
  GoogleSignin.configure({
    webClientId,
    offlineAccess: false,
    forceCodeForRefreshToken: false,
  });
}

export { auth, firestore, GoogleSignin, googleSigninStatusCodes };
export type { FirebaseAuthTypes, FirebaseFirestoreTypes };
